name=Walrus
version=0.2.0
author=Bobby Schulz
sentence=Connect to Walrus pressure sensors
paragraph=Library for the Northern Widget Walrus submersible pressure and temperature sensor.
category=Sensors
url=https://github.com/NorthernWidget-Skunkworks/Walrus_Library
maintainer=Northern Widget
architectures=*

